POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZsYWQiLCJpZCI6IjVmNzczM2UwYjQzZjk2MjI4NDQzNDIxZiIsImlhdCI6MTYwMTk4MTY4N30.PU22qHgddO9aKr1iQLZmXxnmVA8MfThUdzozQKYJDDc

{
  "title": "06.10",
  "author": "me",
  "url": "localhost",
  "likes": 10
}